In [1]:
ls

 O volume na unidade E ‚ Disco Local
 O N£mero de S‚rie do Volume ‚ EC7C-50A7

 Pasta de E:\visao_am

04/05/2024  08:53    <DIR>          .
04/05/2024  08:53    <DIR>          ..
04/05/2024  08:53    <DIR>          .ipynb_checkpoints
04/05/2024  08:52               337 aula_02.ipynb
04/05/2024  08:45    <DIR>          imagens_visao_am
04/05/2024  08:45    <DIR>          visao_am_basico
               1 arquivo(s)            337 bytes
               5 pasta(s)   999.825.752.064 bytes dispon¡veis


In [2]:
pwd

'E:\\visao_am'

In [3]:
list_1 = ['janeiro', 'fevereiro', 'março']

In [8]:
type(list_1)

list

In [4]:
print(list_1)

['janeiro', 'fevereiro', 'março']


In [7]:
x=0
s=0
while x < 25:
    s= s+x
    x= x+1
    print('valor de x: ',x, 'Valor de s: ', s)

valor de x:  1 Valor de s:  0
valor de x:  2 Valor de s:  1
valor de x:  3 Valor de s:  3
valor de x:  4 Valor de s:  6
valor de x:  5 Valor de s:  10
valor de x:  6 Valor de s:  15
valor de x:  7 Valor de s:  21
valor de x:  8 Valor de s:  28
valor de x:  9 Valor de s:  36
valor de x:  10 Valor de s:  45
valor de x:  11 Valor de s:  55
valor de x:  12 Valor de s:  66
valor de x:  13 Valor de s:  78
valor de x:  14 Valor de s:  91
valor de x:  15 Valor de s:  105
valor de x:  16 Valor de s:  120
valor de x:  17 Valor de s:  136
valor de x:  18 Valor de s:  153
valor de x:  19 Valor de s:  171
valor de x:  20 Valor de s:  190
valor de x:  21 Valor de s:  210
valor de x:  22 Valor de s:  231
valor de x:  23 Valor de s:  253
valor de x:  24 Valor de s:  276
valor de x:  25 Valor de s:  300


In [9]:
nome = 'Maria'

In [11]:
nome += "Silva"

In [12]:
nome

'MariaSilva'

In [14]:
list_1 += ['abril']

In [15]:
list_1

['janeiro', 'fevereiro', 'março', 'abril']

In [18]:
list_1 += ['maio']

In [19]:
list_1

['janeiro', 'fevereiro', 'março', 'abril', 'm', 'a', 'i', 'o', 'maio']

In [20]:
list_1.append('junho')

In [21]:
list_1

['janeiro', 'fevereiro', 'março', 'abril', 'm', 'a', 'i', 'o', 'maio', 'junho']

In [22]:
x,y,z = 100, 'tipo', ['a','b','c']

In [23]:
z

['a', 'b', 'c']

In [24]:
z.insert?

Signature: z.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [25]:
z.insert(1, 'w')

In [26]:
z

['a', 'w', 'b', 'c']

In [27]:
v_str = 'Visão computacional'

In [28]:
v_str[4]

'o'

In [29]:
v_str[4:8]

'o co'

In [30]:
v_str[-1]

'l'

In [31]:
v_str[0:8:2]

'Vsoc'

In [32]:
v_str[::-1]

'lanoicatupmoc oãsiV'

In [33]:
print('Aluno', nome, 'cursou a disciplina: ', v_str, ' em', list_1[3])

Aluno MariaSilva cursou a disciplina:  Visão computacional  em abril


In [34]:
list_1[3][0:3]

'abr'

In [39]:
for item in list_1:
    print(x, item)
    x +=1

110 janeiro
111 fevereiro
112 março
113 abril
114 m
115 a
116 i
117 o
118 maio
119 junho


In [45]:
def media_notas(lista):
    return sum(list(lista)/len(lista))
    

In [51]:
ent = ''
list_notas = []
while True:
    ent = input('Digite uma nota ou Q para parar : ')
    if ent == 'Q':
        break
    elif ent.isnumeric():
        list_notas.append(float(ent)
                         )
media = media_notas(list_notas)
list_notas.sort()
print('A média é: ', media)
print('Quantidade de elementos: ', len(list_notas))
print('Menor valor: ', list_notas[0])
print('A média é: ', list_notas[-1])



Digite uma nota ou Q para parar :  7.7
Digite uma nota ou Q para parar :  8.8
Digite uma nota ou Q para parar :  9
Digite uma nota ou Q para parar :  Q


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
# Numpy

In [52]:
import numpy as np

In [53]:
np.__version__

'1.26.4'

In [54]:
m1 = np.array([12, 3, 5, 7, -6, 0])
m2 = np.array([6, 12, 7, 11, 5, 1])

In [55]:
m1 + m2

array([18, 15, 12, 18, -1,  1])

In [56]:
print([n*n for n in range(1000)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 2656

In [58]:
%timeit [n*n for n in range(1000)]

49.1 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [59]:
%timeit np.arange(1000)**2

2.11 µs ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [62]:
def dot(m1, m2):
    s =0
    for i in range(1000):
        s+= m1[i] * m2[i]
    return s

In [64]:
np.dot(m1, m2)

190

In [65]:
n0 = np.array([[0, 1, 2], [4, 5, 6]])

In [67]:
n0

array([[0, 1, 2],
       [4, 5, 6]])

In [66]:
n0.shape

(2, 3)

In [68]:
n0.reshape(3, 2)

array([[0, 1],
       [2, 4],
       [5, 6]])

In [71]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.empty((2, 3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.89143161e-307, 2.67017962e-306, 1.05699581e-307]])

In [72]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])